pkg/embed/shell/30-etc-hosts.sh

**What this PR does / why we need it**: This PR fixes the new `cp` usage to properly overwrite the existing `/etc/hosts`. I use `yes` piped into `cp` in case the shell is interactive, since we could be using busybox or regular POSIX `cp`. 

fix(shell): overwrite /etc/hosts

---

pkg/embed/shell/30-etc-hosts.sh

**What this PR does / why we need it**: This PR changes the behaviour of the `/etc/hosts` modifier in CI, when being ran in a docker container we can't remove `/etc/hosts` because it's being controlled by the docker daemon via a volume mount, but we can append. So, we use the old behaviour of appending to the live /etc/hosts in CI, and do the one-time move logic otherwise (saves on sudo calls) 
**JIRA ID**: [DT-494]
[DT-494]: https://outreach-io.atlassian.net/browse/DT-494

fix: append only to /etc/hosts in CI

---

pkg/embed/shell/30-etc-hosts.sh

**What this PR does / why we need it**: This PR fixes the non-CI `/etc/hosts` behaviour to properly copy to a temp file. 
**Notes for your reviewer**: [**CONTEXT**](https://outreach-hq.slack.com/archives/CN9MU7GLW/p1623881407189600)

fix: copy /etc/hosts properly

---

cmd/devenv/devenv.go
cmd/devenv/provision/provision.go

**What this PR does / why we need it**: This PR adds automatic removal of `:latest` docker images on the configured `box` image registry on `devenv provision`. This was in the OG devenv as users seemed to expect this behaviour, it was slated to be added back post-MVP. So, this adds it back (now in Go!)

feat: remove docker box :latest images on provision

---

.tool-versions
cmd/devenv/provision/provision.go
pkg/embed/config/kind.yaml

**What this PR does / why we need it**: This PR removes the `-it` (interactive, tty) request to the `docker exec` call for removing docker images. This would sometimes trip up and cause the command to fail. 
**Notes for your reviewer**: [**Context**](https://outreach-hq.slack.com/archives/CN9MU7GLW/p1625079167475400)

fix: remove TTY argument in remove images

---

go.mod
go.sum

**What this PR does / why we need it**:
Brings in changes from (below pr) to allow `devenv` to leverage
existing ssh agents when running (no more entering your passphrase every
time!)
https://github.com/getoutreach/gobox/pull/24
**JIRA ID**: noop

fix: update gobox to include ssh agent enhancements

---

README.md

**What this PR does / why we need it**: This PR removes the reference to `--base`, while this is correct for OSS users to use, for Outreach (and people w/ Box configuration) this is not the correct flag.
We'll be revamping this later w/ Bootstrap OSS anyways, so for now let's stop people from hurting themselves.

docs(README): remove base reference

---

cmd/devenv/provision/provision.go
cmd/devenv/provision/snapshot.go
cmd/devenv/snapshot/snapshot.go
cmd/devenv/snapshot/snapshot_generate.go
pkg/box/box.go

**What this PR does / why we need it**: This PR adds support for two different channels: `stable` and `rc`. These can be used to test different snapshot versions. The new lock format also stores snapshots as new ones are added, this can be used, eventually, to allow older snapshots to be re-used in the case of problems.

feat: support channels / history of snapshots

---

cmd/devenv/kubectl/kubectl.go

**What this PR does / why we need it**: This PR fixes `kubectl` to not choke on `--skip-update`, or other devenv specific flags, by using only args after `devenv kubectl`. Unsure why I didn't do this in the first place. 

fix(kubectly): pass correct args to kubectl

---

cmd/devenv/provision/provision.go
pkg/app/deploy.go
pkg/devenvutil/devenv.go

**What this PR does / why we need it**: This PR brings the new generic ready pod wait to `deploy-app`, this should help users, and automated scripts, get a better idea of when a devenv is ready post deploy-app command. It's not perfect, but it's about the best we can do in Kubernetes.
**JIRA ID**: DTSS-0

feat(deploy-app): wait for pods to be ready after deploy

---

cmd/devenv/provision/prepare.go
pkg/devenvutil/devenv.go

By deploying `vcluster-annotator` to all cloud devenvs we are easily able to make all pods be safe to evict via the cluster-autoscaler, enabling GKE to scale down (among other clusters).

feat: deploy vcluster-annotator to all loft devenvs

---

cmd/devenv/start/start.go
cmd/devenv/stop/stop.go
pkg/kubernetesruntime/kind.go
pkg/kubernetesruntime/kubernetesruntime.go
pkg/kubernetesruntime/loft.go

This PR adds support for `devenv stop` and `devenv start` to remote Kubernetes clusters, we also now cleanup loft spaces to prevent extra resources from being left over when a cluster is deleted.
**JIRA ID**: DTSS-0

feat: stop/start remote clusters

---

internal/alert/alert.go

* That function that was being called in it I thought was an initializer for the beeep package. It's not.

fix: remove init func from alert package

---

cmd/devenv/auth-vault/auth.go
cmd/devenv/auth/auth.go
cmd/devenv/auth/refresh.go
cmd/devenv/devenv.go

When vault token in devenv expires, new secrets on deployment don't get created. There's no way to just refresh the token today. `deploy-app` does the trick, but it also applies manifests (in case of cloud devenv, without pushing docker image). This helps mitigate issue with `devspace deploy`.

feat: auth-vault reauthenticates vault operator in devenv

---

cmd/devenv/auth/refresh.go
internal/vault/vault.go

It doesn't work if it can't update kubernetes.

fix: Pass kubernetes client to auth refresh

---

pkg/app/app.go

Don't swallow 404/auth errors when determining the application type. Originally we swallowed errors to detect the type, but when looking for an invalid repo or on invalid auth this would swallow that error and instead return a cryptic ref failure message.

fix(apps): dont swallow auth error

---

cmd/devenv/apps/update/update.go
cmd/devenv/snapshot/snapshot.go
docs/interacting-with-services.md
docs/lifecycle.md

`devenv deploy-app` is deprecated and need to use `devenv apps run` instead 
https://outreach-io.atlassian.net/browse/DTSS-1594

fix: use apps deploy instead of deploy-app

---

pkg/app/common.go
pkg/app/deploy.go

`build-jsonnet.sh` script in `devbase` recognizes the new env variables as it's reused between legacy and devspace deploys. Building docker images using `make docker-build` doesn't.
[DTSS-1593]
[DTSS-1593]: https://outreach-io.atlassian.net/browse/DTSS-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Use box config for image registry in legacy deployments.

---

pkg/devenvutil/devenv.go
pkg/devenvutil/devenv_test.go

Enables more descriptive logging when waiting for pods to complete fails
[DTSS-1735]
[DTSS-1735]: https://outreach-io.atlassian.net/browse/DTSS-1735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: enable pod logging when waiting times out

---

pkg/devenvutil/devenv.go

Devenv provisions are getting _pretty_ slow for some of these E2E tests and other environments, so for now I'm bumping the timeout. Longer-term we might need to figure out a better way to handle this.
[XX-XX]

fix(devenv): bump timeout to 20 minutes

---

Makefile
cmd/devenv/devenv.go
go.mod
internal/shim/kubectl.embed
internal/shim/kubectl.go
internal/shim/kubectl_test.go
internal/shim/shim.go
pkg/app/run.go

User machine `kubectl`, devenv Kubernetes, and devenv `kubectl` can be incompatible. This forces use of fixed, embedded `kubectl` by devenv and child processes it spawns.
[XX-XX]

feat: Shim `kubectl` for child processes

---

go.mod
pkg/devenvutil/devenv.go

**What this PR does**: This PR updates the error message to include the unready pods instead of "context deadline exceeded". This has no real impact on the UX but allows our telemetry to track the unready pods.
Future improvements to make this more indexable should be made, this is done quickly for debugging reasons.

fix: include unready pods in error

---

cmd/devenv/provision/prepare.go
cmd/devenv/provision/provision.go
pkg/kube/logs.go

This PR changes the restic init container deletion code to wait for the pods to finish instead of immediately deleting them. There's some cases where deleting them can result in a bad state instead of waiting. This highlights issues with stuff (such as the CSI migration issues we hit with Velero on GKE) instead of masking it as problems with the underlying cluster (such as pods getting stuck in terminating forever). There's also a few small UX changes in this PR
[XX-XX]

fix(provision): wait for restic init containers to finish

---

cmd/devenv/provision/docker_for_mac.go

**What this PR does**: This PR ensures that docker for mac supports cgroups v1 by modifying the docker configuration.

fix(dfm): ensure cgroups v1 are enabled

---

cmd/devenv/provision/provision.go
pkg/devenvutil/devenv.go

Cleans up the velero namespace after snapshot restore. This should reduce resource use and hopefully allow the loft clusters to scale.
[DTSS-1724]
[DTSS-1724]: https://outreach-io.atlassian.net/browse/DTSS-1724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: cleanup velero namespace
