getoutreach/devenv

LICENSE

**What this PR does / why we need it**: As it says, it does!

docs: add Apache-2.0 license

---

pkg/snapshoter/minio.go

**What this PR does / why we need it**: For some reason the tag we used appears to have been unpublished, so this uses a newer image now.

fix(snapshoter): use valid image

---

.vscode/launch.json
Dockerfile
cmd/devenv/provision/provision.go
cmd/devenv/snapshot/snapshot.go
cmd/devenv/snapshot/snapshot_generate.go
cmd/devenv/status/status.go
deployments/devenv/snapshots/.terraform.lock.hcl
deployments/devenv/snapshots/main.tf
internal/vault/vault.go
pkg/box/fetch.go
pkg/embed/manifests/vault/vault-secrets-operator.jsonnet
pkg/embed/shell/30-etc-hosts.sh
pkg/kubernetesruntime/kind.go

**What this PR does / why we need it**: This PR adds Golang and Vault to the docker image, fixes Vault in CI (vault-dev) and a panic on `devenv status`
**JIRA ID**: [DT-494]
[DT-494]: https://outreach-io.atlassian.net/browse/DT-494

fix(docker): add vault and go to docker image, fix vault & panic

---

README.md

pointing to `docs/system-requirements.md` to avoid a broken link
**What this PR does / why we need it**: fix broken link for system requirements
**JIRA ID**: N/A

docs: fix `System Requirement` link

---

pkg/deployapp/deployapp.go

**What this PR does / why we need it**: Wrong filename error message was shown.

fix: Show real filenames in error message for missing deploy to dev

---

.tool-versions
pkg/kubernetesruntime/kind.go
service.yaml

**What this PR does / why we need it**: This PR upgrades KinD to `0.12.0` from our fork [getoutreach/kind](https://github.com/getoutreach/kind). 
**JIRA ID**: [DTSS-700]
[DTSS-700]: https://outreach-io.atlassian.net/browse/DTSS-700

feat(kind): upgrade KinD to 0.12

---

pkg/kubernetestunnelruntime/localizer.go

**What this PR does / why we need it**: 
* turns out you need to update the go.mod version and this version. whoops

feat: bump localizer version

---

.circleci/config.yml
cmd/devenv/context/context.go

fix: modify ingress after context switching

---

.releaserc.yaml

Title says it does, as per the JIRA ticket we weren't publishing images with a `v` prefix. Now we are.
**JIRA ID**: [DTSS-846]
[DTSS-846]: https://outreach-io.atlassian.net/browse/DTSS-846

fix(ci): publish image with v prefix (DTSS-846)

---

cmd/devenv/destroy/destroy.go

fix(destroy): configure kubernetes runtime on destroy

---

pkg/kubernetesruntime/loft.go

This PR adds support to the devenv for generating direct cluster endpoints for loft clusters. This is the final piece in multi-region support.

feat(loft): support generating direct-cluster-endpoints

---

cmd/devenv/snapshot/snapshot.go

This PR does what the title says. We basically started to snapshot our self when we moved minio into the container randomly increasing the size of the snapshots. Pretty crazy.

fix(snapshot): dont try to snapshot ourself (minio)

---

pkg/kubernetestunnelruntime/localizer.go

feat: update localizer

---

cmd/devenv/devenv.go

[DTSS-429]
fix: Enable devenv completion to work without updating.
**JIRA ID**:DTSS-429
[DTSS-429]: https://outreach-io.atlassian.net/browse/DTSS-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Enable devenv completion to work without updating.

---

pkg/embed/manifests/pre-restore/04_minio.yaml

fix: Using different Minio helm chart

---

pkg/app/app.go

Title says, it does.
**JIRA ID**: DTSS-0

feat(deploy-app): support cloning submodules

---

cmd/devenv/start/start.go
cmd/devenv/tunnel/tunnel.go
go.mod
go.sum
internal/alert/alert.go
pkg/aws/aws.go

* alerts when waiting for sudo prompt or aws login after some time
* bad branch name, sry

feat: alert when waiting for some time

---

cmd/devenv/tunnel/tunnel.go
pkg/aws/aws.go

fix: adjust alert times

---

.circleci/config.yml
pkg/app/app.go

This is better for apps that use `service.yaml` to set dependencies but aren't bootstrapped.

fix(apps): detect bootstrap apps via lockfile

---

cmd/devenv/apps/list/list.go

Sort apps by name, easier to read.

fix(apps/list): sort

---

pkg/app/app.go
pkg/app/deploy.go

This should fix issues with cloning a partial repo that would sometimes flake when trying to checkout

fix(apps): full clone repo to prevent flakiness in checking out

---

cmd/devenv/start/start.go
cmd/devenv/stop/stop.go
pkg/kubernetesruntime/loft.go

This PR fixes `stop` and `start` to supports loft v2.
**JIRA ID**: DTSS-1140

fix: stop and start support loft v1/v2 (DTSS-1140)

---

pkg/app/app.go

This PR fixes the legacy application name resolving logic to consider the absolute path to the local directory. This was bugged on relative paths, e.g. `.` and now handles them properly.
[DTSS-0]

fix(apps/deploy): correctly resolve legacy application names

---

pkg/devenvutil/devenv.go

https://outreach-io.atlassian.net/browse/DTSS-1345
https://outreach-hq.slack.com/archives/CN9MU7GLW/p1645752896502919?thread_ts=1645752790.011719&cid=CN9MU7GLW

feat: Add timeout to WaitForAllPodsToBeReady

---

cmd/devenv/apps/delete/delete.go

fix: resolve relative path when deleting

---

go.mod
go.sum

fix: update gobox

---

pkg/embed/shell/local-app/outlook/manifests.yaml

Also we need to move this to their repo, totally forgot we even had this
[XX-XX]

fix(outlook): update embeded manifest to use cert-manager.io/v1

---

pkg/app/deploy.go

Remove deprecation warning for now

fix: remove deprecation message as its too early

---

CONTRIBUTING.md
cmd/devenv/apps/apps.go
cmd/devenv/apps/delete/delete.go
cmd/devenv/apps/deploy/deploy.go
cmd/devenv/apps/dev/dev.go
cmd/devenv/apps/dev/stop/stop.go
cmd/devenv/provision/prepare.go
cmd/devenv/provision/provision.go
go.mod
go.sum
pkg/app/common.go
pkg/app/delete.go
pkg/app/deploy.go
pkg/app/dev.go
pkg/kubernetesruntime/kind.go
pkg/kubernetesruntime/loft.go

- Put devspace implementation behind a `--x-use-devspace` feature flag for `apps deploy` & `apps delete`
- Implement `apps dev` & `apps dev stop`
- Implement `apps delete` using devspace
- Fixes arg passed to deploy fallback scripts from `deploy` to `update` as that's used now.
[DTSS-1451]
[DTSS-1452]
[DTSS-1453]
[DTSS-1458]
[DTSS-1451]: https://outreach-io.atlassian.net/browse/DTSS-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DTSS-1452]: https://outreach-io.atlassian.net/browse/DTSS-1452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DTSS-1453]: https://outreach-io.atlassian.net/browse/DTSS-1453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

feat(devspace): Added `apps dev` and `apps delete` commands.

---

pkg/embed/manifests/pre-restore/cert-manager.yaml

feat: merge main to rc

---

cmd/devenv/status/status.go

fix: Merge with main

---

cmd/devenv/apps/dev/dev.go
pkg/app/dev.go

Passing `$DEVENV_DEPLOY_APP_PROFILE` to `devspace` lets us start the right binary, replace the right deployment ...
Other PRs to make it work e2e:
- https://github.com/getoutreach/bootstrap/pull/1108
- https://github.com/getoutreach/devbase/pull/161
[DTSS-1466]
[DTSS-1466]: https://outreach-io.atlassian.net/browse/DTSS-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(devspace): `apps dev --app` sets `$DEVENV_DEV_DEPLOYMENT_PROFILE`

---

cmd/devenv/apps/apps.go
cmd/devenv/apps/dev/dev.go
cmd/devenv/apps/run/run.go
cmd/devenv/apps/run/stop/stop.go
pkg/app/run.go

fix: Renamed `dev` to `run`

---

pkg/kubernetestunnelruntime/localizer.go

This PR updates localizer so that we can get rid of the "failed to write" logs 🎉 
[XX-XX]

fix(tunnel): update localizer to improve tunnel UX

---

pkg/kubernetestunnelruntime/localizer.go

feat: Merge `main` to `rc`

---

cmd/devenv/apps/deploy/deploy.go
pkg/app/app.go
pkg/app/common.go
pkg/app/deploy.go

When deploying dependencies (e.g. `devenv apps deploy --x-use-devspace outreach`) the same deployment method should be used.
[XX-XX]

feat(devspace): Propagate `--x-use-devspace` flag to child processes.

---

pkg/app/common.go

fix: Use devspace v5.18.4

---

cmd/devenv/apps/apps.go
cmd/devenv/apps/shell/shell.go
pkg/app/common.go
pkg/app/shell.go

Easy way to open a shell into your dev container.
[DTSS-1466]
[DTSS-1466]: https://outreach-io.atlassian.net/browse/DTSS-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(devspace): Added a way to open terminal into dev container.

---

cmd/devenv/apps/shell/shell.go
pkg/app/common.go

fix: Muti-namespace deployments

---

cmd/devenv/provision/docker_for_mac.go

feat: dont override cpu or memory if greater than reccomended

---

.goreleaser.yml

Makes telemetry work with released bin
[DTSS-1629]
[DTSS-1629]: https://outreach-io.atlassian.net/browse/DTSS-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Added releaser TELEFORK_APIKEY var

---

.goreleaser.yml

fix: Releaser config template

---

pkg/app/common.go

`devtel` sends devspace specific telemetry to Datadog. Here we try to install the plugin.
[XX-XX]

feat(devspace): Install devtel plugin for more telemetry.

---

cmd/devenv/apps/run/run.go
pkg/app/run.go

When there's a port clash, without this devs are blocked.
[DTSS-1712]
[DTSS-1712]: https://outreach-io.atlassian.net/browse/DTSS-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(devspace): Skip port forwarding on `apps run`

---

cmd/devenv/apps/run/run.go
pkg/app/run.go
pkg/kubernetesruntime/loft.go

fix: Loft login didn't run on provision/start/stop

---

cmd/devenv/destroy/destroy.go
cmd/devenv/provision/provision.go

[DTSS-1717]
[DTSS-1717]: https://outreach-io.atlassian.net/browse/DTSS-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Added devenv runtime kind to provision & destroy telemetry

---

docs/config/_default/menus/menus.en.toml

Page doesn't exist yet, so remove the header item.

docs: remove getting-started header

---

.goreleaser.yml

fix: Set the right version for kubectl lib in goreleaser

---

pkg/kubernetesruntime/loft.go

**What this PR does**: Title says, it does. :D

chore: upgrade loft cli to v2.2.0

---

go.mod
go.sum
pkg/embed/manifests/pre-restore/04_minio.yaml
pkg/embed/manifests/pre-restore/04_velero.jsonnet
pkg/embed/manifests/pre-restore/metrics-server.yaml
pkg/embed/manifests/pre-restore/nginx-ingress.jsonnet
pkg/embed/manifests/pre-restore/vault-secrets-operator.jsonnet

fix: update deps

---

pkg/app/common.go

fix: bump devspace

---

cmd/devenv/apps/apps.go
cmd/devenv/apps/e2e/e2e.go
pkg/app/e2e.go
pkg/app/run.go

Adds a `devenv apps e2e` command to run e2e tests inside devspace.
[DTSS-1601]
[DTSS-1601]: https://outreach-io.atlassian.net/browse/DTSS-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add apps e2e command
